### ISSUE TITLE
Modify contact to point to this repo 

### ISSUE THREAD

**Issue by pachulo** [snapcrafters/postman#1]
The postman snap contact is still pointing the old repo not this one:

```
⟫ snap info postman 
name:      postman
summary:   API Development Environment
publisher: snapcrafters
contact:   https://github.com/junglerobba/postman-snap

...
```

**Comment by junglerobba** [comment]
Apparently I still have dashboard access, so I updated the contact to this repo. Should be correct now.

**Comment by pachulo** [comment]
Now it's correct, thanks!
