### ISSUE TITLE
Trigger build to update to 6.2.5

### ISSUE THREAD

**Issue by pachulo** [snapcrafters/postman#2]

**Comment by neclimdul** [comment]
6.3.0 now...

**Comment by popey** [comment]
Thanks for the pings. Build triggered. https://launchpad.net/~build.snapcraft.io/+snap/2773749cc6668816fc32f2debfc88c70-xenial

**Comment by popey** [comment]
Built, tested and released 6.3.0 to stable. Thanks again @pachulo and @neclimdul
