### ISSUE TITLE
Update Postman snap to latest stable version 6.4.4

### ISSUE THREAD

**Issue by Spurlos** [snapcrafters/postman#7]
Postman snap tries to autoupdate itself to latest version (6.4.4) and failing. Looks like you need to update the snap package in repos to latest stable version. Until then we must use plain old .deb package to get latest stuff and bugfixes.
![image](https://user-images.githubusercontent.com/667533/47214280-15e28a00-d3a6-11e8-8725-f2126599477e.png)

**Comment by popey** [comment]
Thanks for letting us know. Unfortunately one of the node modules used by postman (colors) has an erroneous file (.colors.js.swp) in it, which causes the snap to get rejected when it's uploaded to the store. So I have made a PR to manually rm that file, once that lands, I'll trigger a build and we'll get it tested and published. Sorry for the inconvenience.

**Comment by popey** [comment]
Ok, fixed the build and it's now tested and in the stable channel. Thanks again @Spurlos
